layout: "main"
logger: "file"
appname: "webif"
session: YAML
template: template_toolkit
engines:
    template_toolkit:
        start_tag: '[%'
        stop_tag: '%]'
plugins:
    Database:
        driver: SQLite
        database: "webif.sqlite"
        dbi_params:
            RaiseError: 1
