package Intercensor::Model::DB;

use Moose;

extends 'Catalyst::Model::DBIC::Schema';

use CLASS;

CLASS->config(
    schema_class => 'Intercensor::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:intercensor.db',
        user => '',
        password => '',
        on_connect_do => [
            'PRAGMA foreign_keys = ON',
            'PRAGMA PRAGMA journal_mode = WAL',
        ],
    }
);

=head1 NAME

Intercensor::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Intercensor>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Intercensor::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.49

=head1 AUTHOR

Maximilian Gass

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
